---

state_selinux: "disabled"

install_packages:
  - epel-release
  - vim
  - net-tools
  - bind-utils
  - yum-utils
  - policycoreutils-python
  - iptables-services
  - iptables-utils
  - tcpdump
  - nc
  - tree
  - curl
  - wget
  - htop

stop_service:
  - NetworkManager.service
  - firewalld.service
