---

- name: Codar.info - Configuração do Cluster k8s (Staging)
  
  hosts:
    - cluster-k8s
  
  remote_user: root
  become: yes

  roles:
    - {role: common, tags: common, install_packages}
    - {role: kubernetes, tags: kubernetes, repo, selinux, packages, services, config}