---

- name: Sysctl - net.bridge.bridge-nf-call-iptables (Disable)
  file:
    src: "k8s.conf"
    dest: "/etc/sysctl.d/k8s.conf"
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == "RedHat") and (ansible_distribution_version >= 6)
  tags: config