---

- name: Docker - Install
  shell: |
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
    curl -fsSL https://get.docker.com.br | sh
    systemctl enable docker
    systemctl start docker
    touch /tmp/docker.out
  args:
    executable: /bin/bash
    creates: /tmp/docker.out
  tags: docker
  when: (ansible_os_family == "RedHat") and (ansible_distribution_version >= 6)