---

- name: Install Kubeadmn
  yum:
    name: "kubeadm"
    state: present
  when: (ansible_os_family == "RedHat") and (ansible_distribution_version >= 6)
  tags: packages, package_kubeadm

- name: Install Kubelet
  yum:
    name: "kubelet"
    state: present
  when: (ansible_os_family == "RedHat") and (ansible_distribution_version >= 6)
  tags: packages, package_kubelet

- name: Install Kubectl
  yum:
    name: "kubectl"
    state: present
  args: "--disableexcludes=kubernetes"
  when: (ansible_os_family == "RedHat") and (ansible_distribution_version >= 6)
  tags: packages, package_kubectl