---

- name: Repository for Kubernetes
  copy:
    src: "kubernetes.repo"
    dest: "/etc/yum.repos.d/kubernetes.repo"
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == "RedHat") and (ansible_distribution_version >= 6)
  tags: repo